/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Live
         * @description Liveness is process-level and must not depend on storage health.
         */
        get: operations["health_live_api_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Ready
         * @description Readiness reports each dependency and returns 503 when degraded.
         */
        get: operations["health_ready_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog */
        get: operations["catalog_api_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Scenario */
        post: operations["validate_scenario_api_scenarios_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inspect */
        post: operations["inspect_api_scenarios_inspect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Estimate Run */
        post: operations["estimate_run_api_runs_estimate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__job_id__get"];
        put?: never;
        post?: never;
        /** Cancel Run */
        delete: operations["cancel_run_api_runs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{job_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Result */
        get: operations["get_run_result_api_runs__job_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sweeps/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Estimate Sweep */
        post: operations["estimate_sweep_api_sweeps_estimate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sweeps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Sweep */
        post: operations["create_sweep_api_sweeps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sweeps/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sweep */
        get: operations["get_sweep_api_sweeps__job_id__get"];
        put?: never;
        post?: never;
        /** Cancel Sweep */
        delete: operations["cancel_sweep_api_sweeps__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sweeps/{job_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sweep Result
         * @description Load a completed sweep DTO on demand, never through status polling.
         */
        get: operations["get_sweep_result_api_sweeps__job_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characterize/{section}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Characterize */
        post: operations["characterize_api_characterize__section__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dynamics/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: operations["preview_api_dynamics_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Experiments */
        get: operations["list_experiments_api_experiments_get"];
        put?: never;
        /** Create Experiment */
        post: operations["create_experiment_api_experiments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Experiment */
        get: operations["get_experiment_api_experiments__experiment_id__get"];
        /** Replace Experiment */
        put: operations["replace_experiment_api_experiments__experiment_id__put"];
        post?: never;
        /** Delete Experiment */
        delete: operations["delete_experiment_api_experiments__experiment_id__delete"];
        options?: never;
        head?: never;
        /** Update Experiment */
        patch: operations["update_experiment_api_experiments__experiment_id__patch"];
        trace?: never;
    };
    "/api/experiments/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Experiment */
        post: operations["import_experiment_api_experiments_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Experiment */
        get: operations["export_experiment_api_experiments__experiment_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Presets */
        get: operations["presets_api_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AxisInput */
        AxisInput: {
            /** Target */
            target?: string | null;
            /** Values */
            values?: unknown | null;
            /** Time Axis */
            time_axis?: unknown | null;
        } & {
            [key: string]: unknown;
        };
        /** CancellationResponse */
        CancellationResponse: {
            /** Cancelled */
            cancelled: boolean;
            /** Cancellation Requested */
            cancellation_requested?: boolean | null;
            /** Status */
            status?: ("queued" | "running" | "cancellation_requested" | "cancelled" | "timed_out" | "done" | "error" | "interrupted" | "expired") | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * CatalogFieldMetadata
         * @description Additive scientific metadata carried alongside legacy catalog fields.
         */
        CatalogFieldMetadata: {
            /** Key */
            key: string;
            /** Default */
            default?: unknown | null;
            /** Unit */
            unit?: string | null;
            /** Options */
            options?: string[] | null;
            /** Visible When */
            visible_when?: {
                [key: string]: unknown;
            } | null;
            /** Conditions */
            conditions?: {
                [key: string]: unknown;
            } | null;
            /** Dependencies */
            dependencies?: string[];
            /** Applicable Protocols */
            applicable_protocols?: string[];
            /** Applicable Source Kinds */
            applicable_source_kinds?: string[];
            /** Applicable Channel Kinds */
            applicable_channel_kinds?: string[];
            /** Applicable Detector Kinds */
            applicable_detector_kinds?: string[];
        } & {
            [key: string]: unknown;
        };
        /**
         * CatalogResponse
         * @description Versioned catalog envelope; legacy keys remain permissive/additive.
         */
        CatalogResponse: {
            /** Metadata Version */
            metadata_version?: number | null;
            /** Default Medium Id */
            default_medium_id?: string | null;
            /** Default Scenario */
            default_scenario?: {
                [key: string]: unknown;
            } | null;
            /** Field Defaults */
            field_defaults?: {
                [key: string]: unknown;
            };
            /** Fields */
            fields?: components["schemas"]["CatalogFieldMetadata"][];
            /** Media */
            media?: {
                [key: string]: unknown;
            }[];
            /** Sections */
            sections?: {
                [key: string]: unknown;
            }[];
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            }[];
            /** Capabilities */
            capabilities?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /**
         * CompactSweepResultResponse
         * @description Versioned, metadata-factorized sweep artifact returned on demand.
         */
        CompactSweepResultResponse: {
            /**
             * Schema Version
             * @constant
             */
            schema_version: 2;
            /**
             * Row Encoding
             * @constant
             */
            row_encoding: "scalar-records-v1";
            /** Row Count */
            row_count: number;
            /** Requested Scenario Digest */
            requested_scenario_digest: string;
            /** Provenance */
            provenance: {
                [key: string]: unknown;
            };
            /** Assessment */
            assessment: {
                [key: string]: unknown;
            };
            /** Effective Model */
            effective_model: {
                [key: string]: unknown;
            };
            /** Row Invariants */
            row_invariants: {
                [key: string]: boolean | number | string | null;
            };
            /** Rows */
            rows: {
                [key: string]: boolean | number | string | null;
            }[];
            /** Provenance Columns */
            provenance_columns?: {
                [key: string]: unknown;
            };
            /** Provenance Missing */
            provenance_missing?: {
                [key: string]: number[];
            };
            /** Assessment Columns */
            assessment_columns?: {
                [key: string]: unknown;
            };
            /** Assessment Missing */
            assessment_missing?: {
                [key: string]: number[];
            };
            /** Effective Model Columns */
            effective_model_columns?: {
                [key: string]: unknown;
            };
            /** Effective Model Missing */
            effective_model_missing?: {
                [key: string]: number[];
            };
            summary: components["schemas"]["CompactSweepSummaryResponse"];
        };
        /** CompactSweepSummaryResponse */
        CompactSweepSummaryResponse: {
            /**
             * Schema Version
             * @constant
             */
            schema_version: 2;
            /** Row Count */
            row_count: number;
            /** Columns */
            columns: {
                [key: string]: (boolean | number | string | null)[];
            };
            /** Missing */
            missing?: {
                [key: string]: number[];
            };
        };
        /** CostEstimateResponse */
        CostEstimateResponse: {
            /**
             * Estimate Kind
             * @constant
             */
            estimate_kind: "upper_bound";
            /** Evaluations */
            evaluations: number;
            /** Pulses Per Evaluation */
            pulses_per_evaluation: number;
            /** Total Pulse Events */
            total_pulse_events: number;
            /** Estimated Max Circuits */
            estimated_max_circuits: number;
            /** Shots Per Circuit */
            shots_per_circuit: number;
            /** Estimated Max Shots */
            estimated_max_shots: number;
            /** Estimated Stored Events */
            estimated_stored_events: number;
            /**
             * Backend
             * @enum {string}
             */
            backend: "statevector" | "aer" | "mixed";
            /** Full Event Log */
            full_event_log: boolean;
            /** Warnings */
            warnings: string[];
        } & {
            [key: string]: unknown;
        };
        /** DeletionResponse */
        DeletionResponse: {
            /** Deleted */
            deleted: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ExperimentCreateRequest */
        ExperimentCreateRequest: {
            scenario?: components["schemas"]["ScenarioInput"] | null;
            /**
             * Name
             * @default Experimento sin titulo
             */
            name: string;
            /** Tags */
            tags?: string[];
            /**
             * Schema Version
             * @default 2
             */
            schema_version: number;
            last_result?: components["schemas"]["ExperimentResult"] | null;
            /** Curve Recipes */
            curve_recipes?: {
                [key: string]: unknown;
            }[];
            /** Runs */
            runs?: components["schemas"]["ExperimentRun"][];
            /** Curves */
            curves?: components["schemas"]["ExperimentCurve"][];
            /** Provenance */
            provenance?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /**
         * ExperimentCurve
         * @description Common curve DTO; metric/axis details remain producer-extensible.
         */
        ExperimentCurve: {
            /** Job Id */
            job_id?: string | null;
            /** Jobid */
            jobId?: string | null;
            /** Curve Id */
            curve_id?: string | null;
            /** Id */
            id?: string | null;
            /** Metric */
            metric?: string | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** ExperimentEnvelopeResponse */
        ExperimentEnvelopeResponse: {
            experiment: components["schemas"]["ExperimentResponse"];
        } & {
            [key: string]: unknown;
        };
        /** ExperimentImportRequest */
        ExperimentImportRequest: {
            /** Experiment */
            experiment?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ExperimentListResponse
         * @description Backward-compatible envelope containing lightweight summaries.
         */
        ExperimentListResponse: {
            /** Experiments */
            experiments: components["schemas"]["ExperimentSummary"][];
            pagination?: components["schemas"]["ExperimentPagination"] | null;
        } & {
            [key: string]: unknown;
        };
        /** ExperimentPagination */
        ExperimentPagination: {
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Total */
            total: number;
            /** Has More */
            has_more: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ExperimentResponse */
        ExperimentResponse: {
            /** Id */
            id: string;
            /**
             * Origin
             * @constant
             */
            origin: "user";
            /** Name */
            name: string;
            /**
             * Schema Version
             * @default 2
             */
            schema_version: number;
            /** Digest */
            digest: string;
            /** Scenario */
            scenario: {
                [key: string]: unknown;
            };
            /** Tags */
            tags: string[];
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            last_result?: components["schemas"]["ExperimentResult"] | null;
            /** Curve Recipes */
            curve_recipes?: {
                [key: string]: unknown;
            }[];
            /** Runs */
            runs?: components["schemas"]["ExperimentRun"][];
            /** Curves */
            curves?: components["schemas"]["ExperimentCurve"][];
            /** Provenance */
            provenance?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /**
         * ExperimentResult
         * @description Result summary DTO with typed evidence sections.
         */
        ExperimentResult: {
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            } | null;
            /** Provenance */
            provenance?: {
                [key: string]: unknown;
            } | null;
            /** Classical */
            classical?: {
                [key: string]: unknown;
            } | null;
            /** Qiskit */
            qiskit?: {
                [key: string]: unknown;
            } | null;
            /** Decoy */
            decoy?: {
                [key: string]: unknown;
            } | null;
            /** Bell */
            bell?: {
                [key: string]: unknown;
            } | null;
            /** Event Sample */
            event_sample?: {
                [key: string]: unknown;
            }[] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ExperimentRun
         * @description Common run DTO; extra fields preserve producer-specific evidence.
         */
        ExperimentRun: {
            /** Job Id */
            job_id?: string | null;
            /** Jobid */
            jobId?: string | null;
            /** Run Id */
            run_id?: string | null;
            /** Id */
            id?: string | null;
            /** Digest */
            digest?: string | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ExperimentSummary
         * @description List representation that intentionally omits scenario/results/logs.
         */
        ExperimentSummary: {
            /** Id */
            id: string;
            /**
             * Origin
             * @constant
             */
            origin: "user";
            /** Name */
            name: string;
            /** Schema Version */
            schema_version: number;
            /** Digest */
            digest: string;
            /** Tags */
            tags: string[];
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /**
             * Runs Count
             * @default 0
             */
            runs_count: number;
            /**
             * Curves Count
             * @default 0
             */
            curves_count: number;
        };
        /** ExperimentUpdateRequest */
        ExperimentUpdateRequest: {
            /** Name */
            name: string;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobArtifactResponse */
        JobArtifactResponse: {
            /** Digest */
            digest?: string | null;
            /** Size Bytes */
            size_bytes: number;
        } & {
            [key: string]: unknown;
        };
        /** JobProgressResponse */
        JobProgressResponse: {
            /** Done */
            done: number;
            /** Total */
            total: number;
        } & {
            [key: string]: unknown;
        };
        /** JobStatusResponse */
        JobStatusResponse: {
            /** Job Id */
            job_id: string;
            /** Kind */
            kind: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "cancellation_requested" | "cancelled" | "timed_out" | "done" | "error" | "interrupted" | "expired";
            progress: components["schemas"]["JobProgressResponse"];
            /** Elapsed S */
            elapsed_s: number;
            timestamps: components["schemas"]["JobTimestampsResponse"];
            /** Timed Out */
            timed_out?: boolean | null;
            /** Error */
            error?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Issues */
            issues?: {
                [key: string]: unknown;
            }[] | null;
            artifact?: components["schemas"]["JobArtifactResponse"] | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Result Summary */
            result_summary?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** JobTimestampsResponse */
        JobTimestampsResponse: {
            /** Created At */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /** Expired At */
            expired_at?: string | null;
            /** Updated At */
            updated_at: string;
        } & {
            [key: string]: unknown;
        };
        /** PresetResponse */
        PresetResponse: {
            /** Name */
            name: string;
            /** Digest */
            digest: string;
            /** Scenario */
            scenario: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** PresetsResponse */
        PresetsResponse: {
            /** Presets */
            presets?: components["schemas"]["PresetResponse"][];
        } & {
            [key: string]: unknown;
        };
        /** RunCreatedResponse */
        RunCreatedResponse: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "cancellation_requested" | "cancelled" | "timed_out" | "done" | "error" | "interrupted" | "expired";
            /** Digest */
            digest: string;
            cost_estimate: components["schemas"]["CostEstimateResponse"];
        } & {
            [key: string]: unknown;
        };
        /** RunRequest */
        RunRequest: {
            scenario?: components["schemas"]["ScenarioInput"] | null;
            /** Label */
            label?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ScenarioInput
         * @description Typed scenario envelope; domain dataclasses remain the source of truth.
         */
        ScenarioInput: {
            /** Schema Version */
            schema_version?: number | null;
            /** Pulses */
            pulses?: number | null;
            /** Clock Rate Hz */
            clock_rate_hz?: number | null;
            /** Seed */
            seed?: number | null;
            /** Protocol */
            protocol?: unknown | null;
            /** Source */
            source?: unknown | null;
            /** Channel */
            channel?: unknown | null;
            /** Detector */
            detector?: unknown | null;
            /** Timing */
            timing?: unknown | null;
            /** Post Processing */
            post_processing?: unknown | null;
            /** Eavesdropper */
            eavesdropper?: unknown | null;
            /** E91 */
            e91?: unknown | null;
            /** Dynamic */
            dynamic?: unknown | null;
            /** Event Sample Size */
            event_sample_size?: number | null;
            /** Store Full Event Log */
            store_full_event_log?: boolean | null;
            /** Metadata */
            metadata?: unknown | null;
        } & {
            [key: string]: unknown;
        };
        /** ScenarioInspectRequest */
        ScenarioInspectRequest: {
            scenario?: components["schemas"]["ScenarioInput"] | null;
        } & {
            [key: string]: unknown;
        };
        /** ScenarioInspectionResponse */
        ScenarioInspectionResponse: {
            /** Valid */
            valid: boolean;
            /** Digest */
            digest: string;
            /** Scenario */
            scenario: {
                [key: string]: unknown;
            };
            /** Warnings */
            warnings: {
                [key: string]: unknown;
            }[];
            /** Effective Digest */
            effective_digest: string;
            /** Effective Scenario */
            effective_scenario: {
                [key: string]: unknown;
            };
            /** Resolution Time S */
            resolution_time_s: number;
            /** Characterizations */
            characterizations: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            cost_estimate: components["schemas"]["CostEstimateResponse"];
        } & {
            [key: string]: unknown;
        };
        /**
         * ScenarioRequest
         * @description Common request shape; extra fields keep bare-scenario compatibility.
         */
        ScenarioRequest: {
            scenario?: components["schemas"]["ScenarioInput"] | null;
        } & {
            [key: string]: unknown;
        };
        /** ScenarioValidationResponse */
        ScenarioValidationResponse: {
            /** Valid */
            valid: boolean;
            /** Digest */
            digest: string;
            /** Scenario */
            scenario: {
                [key: string]: unknown;
            };
            /** Warnings */
            warnings: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        /**
         * SweepCostEstimateResponse
         * @description Sweep estimate adds compact payload/artifact admission bounds.
         */
        SweepCostEstimateResponse: {
            /**
             * Estimate Kind
             * @constant
             */
            estimate_kind: "upper_bound";
            /** Evaluations */
            evaluations: number;
            /** Pulses Per Evaluation */
            pulses_per_evaluation: number;
            /** Total Pulse Events */
            total_pulse_events: number;
            /** Estimated Max Circuits */
            estimated_max_circuits: number;
            /** Shots Per Circuit */
            shots_per_circuit: number;
            /** Estimated Max Shots */
            estimated_max_shots: number;
            /** Estimated Stored Events */
            estimated_stored_events: number;
            /**
             * Backend
             * @enum {string}
             */
            backend: "statevector" | "aer" | "mixed";
            /** Full Event Log */
            full_event_log: boolean;
            /** Warnings */
            warnings: string[];
            /** Estimated Payload Bytes */
            estimated_payload_bytes: number;
            /** Estimated Artifact Bytes */
            estimated_artifact_bytes: number;
            /** Estimated Total Bytes */
            estimated_total_bytes: number;
        } & {
            [key: string]: unknown;
        };
        /** SweepCreatedResponse */
        SweepCreatedResponse: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "cancellation_requested" | "cancelled" | "timed_out" | "done" | "error" | "interrupted" | "expired";
            cost_estimate: components["schemas"]["SweepCostEstimateResponse"];
        } & {
            [key: string]: unknown;
        };
        /** SweepRequest */
        SweepRequest: {
            scenario?: components["schemas"]["ScenarioInput"] | null;
            axis?: components["schemas"]["AxisInput"] | null;
            series?: components["schemas"]["AxisInput"] | null;
            /**
             * Repeats
             * @default 1
             */
            repeats: unknown;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_live_api_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_ready_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    catalog_api_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogResponse"];
                };
            };
        };
    };
    validate_scenario_api_scenarios_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioInspectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioValidationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_api_scenarios_inspect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioInspectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioInspectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    estimate_run_api_runs_estimate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostEstimateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_runs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancellationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_result_api_runs__job_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    estimate_sweep_api_sweeps_estimate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SweepRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SweepCostEstimateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_sweep_api_sweeps_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SweepRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SweepCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sweep_api_sweeps__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_sweep_api_sweeps__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancellationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sweep_result_api_sweeps__job_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompactSweepResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    characterize_api_characterize__section__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                section: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_dynamics_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_experiments_api_experiments_get: {
        parameters: {
            query?: {
                /** @description Maximum number of experiment summaries to return (default 50). */
                limit?: number | null;
                /** @description Number of valid experiment summaries to skip. */
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_experiment_api_experiments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentEnvelopeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_experiment_api_experiments__experiment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentEnvelopeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_experiment_api_experiments__experiment_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentEnvelopeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_experiment_api_experiments__experiment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_experiment_api_experiments__experiment_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentEnvelopeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_experiment_api_experiments_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentEnvelopeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_experiment_api_experiments__experiment_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentEnvelopeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    presets_api_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetsResponse"];
                };
            };
        };
    };
}
